tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'QZSYJYT-ALB66033.snowflakecomputing.com'
      user: 'github_actions_service_user'
      role: GITHUB_ACTIONS_ROLE
      database: tasty_bytes_dbt_db
      schema: DEV
      warehouse: tasty_bytes_dbt_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: tasty_bytes_dbt_wh
